const express = require('express');
const router = express.Router();
const studentRoutes = require('./studentRoutes');
const academicYearRoutes = require('./academicYearRoutes');
const termRoutes = require('./termRoutes');
const classRoutes = require('./classRoutes');
const departmentRoutes = require('./departmentRoutes');
const subjectRoutes = require('./subjectRoutes');
const classSubjectRoutes = require('./classSubjectRoutes');
const studentAttendanceRoutes = require('./studentAttendanceRoutes');
const teacherAttendanceRoutes = require('./teacherAttendanceRoutes');
const financeRoutes = require('./financeRoutes');
const examRoutes = require('./examRoutes');
const announcementRoutes = require('./announcementRoutes');
const portalRoutes = require('./portalRoutes');
const libraryRoutes = require('./libraryRoutes');
const hostelRoutes = require('./hostelRoutes');
const transportRoutes = require('./transportRoutes');
const hrRoutes = require('./hrRoutes');

router.use('/students', studentRoutes);
router.use('/academic-years', academicYearRoutes);
router.use('/terms', termRoutes);
router.use('/classes', classRoutes);
router.use('/departments', departmentRoutes);
router.use('/subjects', subjectRoutes);
router.use('/class-subjects', classSubjectRoutes);
router.use('/attendance/students', studentAttendanceRoutes);
router.use('/attendance/teachers', teacherAttendanceRoutes);
router.use('/finance', financeRoutes);
router.use('/exams', examRoutes);
router.use('/announcements', announcementRoutes);
router.use('/portal', portalRoutes);
router.use('/library', libraryRoutes);
router.use('/hostel', hostelRoutes);
router.use('/transport', transportRoutes);
router.use('/hr', hrRoutes);

module.exports = router;